version: '3.1'
services:
  api:
    image: 'overonix-exchanger-test.jar'
    build: .
    ports:
      - "8080:8080"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5