spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: overonix
    password: xinorevo
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha